### ISSUE TITLE
spring 1

### ISSUE THREAD

**Issue by YULIYA2001** [FiNTiKUglY/pract#11]
Я не говорю сразу исправлять, просто хочу услышать Ваше объяснение: почему так, а не по-другому.

- [x]  Не совсем поняла наличие пакетов entities и models. Почему не в одном? Я встречала источники, которые предлагают названия model, bean, entity как альтернативные. 
- [ ] Sonar для spring должен быть чистым
- [ ] Почитайте про @RequestMapping("") над классом контроллера, чтобы не дублировать пути в каждом отдельном методе класса

Продолжение следует...

**Comment by FiNTiKUglY** [comment]
1. models использую как viewmodel скорее, entity использую как сущности таблицы
2. Исправил
3. Поменял
