### ISSUE TITLE
Sonar точно работает?

### ISSUE THREAD

**Issue by YULIYA2001** [FiNTiKUglY/pract#12]
Сонар должен был рекомендовать перевесить @Autowired на конструктор. 
Можно включить плагин SonarLint в Intellij Ideaб если он не включен.

https://github.com/FiNTiKUglY/pract/blob/f4d84254f8b5e10bd430494e6d90b9c33c0e7d76/libraryapi/src/main/java/com/library/api/libraryapi/services/AuthorService.java#L14C1-L18C6

**Comment by FiNTiKUglY** [comment]
sonarlint предлагает повесить его в самой иде (vs code), но на сайте претензий к этому не имеет

**Comment by FiNTiKUglY** [comment]
поменять?

**Comment by YULIYA2001** [comment]
IDE не просто так подсвечивает, она старается сделать код более чистым и читаемым

**Comment by FiNTiKUglY** [comment]
Исправил, но теперь оно предлагает вообще его убрать как Unnecessary @Autowired, может быть просто внести репозитории в конструктор и вообще убрать Autowired?

**Comment by YULIYA2001** [comment]
Такой вариант предлагает убрать @Autowired?

```
AuthorRepository authorRepository;

    @Autowired
    public AuthorService(AuthorRepository authorRepository) {
        this.authorRepository = authorRepository;
    }
```

**Comment by FiNTiKUglY** [comment]
Да

**Comment by YULIYA2001** [comment]
Раз предлагает убрать, значит можно убрать - видимо, магия аннотаций сама подтянет
Но если работать перестанет, то придется вернуть) Поэтому как хотите, можете оставить, можете попробовать убрать

**Comment by YULIYA2001** [comment]
Там внимательно! Перенести нужно не просто аннотацию на конструктор, но и параметр в конструктор. Как код в сообщении выше
