### ISSUE TITLE
authorRepository.findById(id) может вернуть null -> нужна проверка

### ISSUE THREAD

**Issue by YULIYA2001** [FiNTiKUglY/pract#13]
SonarLint это подсветил бы)

https://github.com/FiNTiKUglY/pract/blob/f4d84254f8b5e10bd430494e6d90b9c33c0e7d76/libraryapi/src/main/java/com/library/api/libraryapi/services/AuthorService.java#L28C1-L30C6

**Comment by FiNTiKUglY** [comment]
Исправил во всех сервисах
