### ISSUE TITLE
Можно оптимизировать

### ISSUE THREAD

**Issue by YULIYA2001** [FiNTiKUglY/pract#14]
genreRepository.saveAll(genres);

https://github.com/FiNTiKUglY/pract/blob/f4d84254f8b5e10bd430494e6d90b9c33c0e7d76/libraryapi/src/main/java/com/library/api/libraryapi/services/BookService.java#L53C13-L55C14

и то же, что в AuthorService

**Comment by FiNTiKUglY** [comment]
Исправил
