### ISSUE TITLE
Note (можно не править)

### ISSUE THREAD

**Issue by YULIYA2001** [FiNTiKUglY/pract#15]
Это, конечно, дело вкуса, но такое обычно называют getBooksByAuthor / getBooksByAuthorId

https://github.com/FiNTiKUglY/pract/blob/f4d84254f8b5e10bd430494e6d90b9c33c0e7d76/libraryapi/src/main/java/com/library/api/libraryapi/services/BookService.java#L30C23-L30C37

**Comment by FiNTiKUglY** [comment]
Принял к сведению
