### ISSUE TITLE
Есть вариант, что пустая сущность передается

### ISSUE THREAD

**Issue by YULIYA2001** [FiNTiKUglY/pract#16]
Вы пытаетесь найти автора по айди, в случае неудачи (нет автора с таким айди) просто передаете дальше на уровень контроллера и на фронт пустышку? Где проверяется потом, что это пустышка.

https://github.com/FiNTiKUglY/pract/blob/a21883daae04ec454b38ea8dd10fc44c7c0b99c6/libraryapi/src/main/java/com/library/api/libraryapi/services/AuthorService.java#L30C1-L37C6

 Альтернатива - выбросить not found прямо в сервисе.

**Comment by FiNTiKUglY** [comment]
Выполнил, нигде больше не передаётся
