### ISSUE TITLE
Точно все верно или копипаст подвел?

### ISSUE THREAD

**Issue by YULIYA2001** [FiNTiKUglY/pract#18]
https://github.com/FiNTiKUglY/pract/blob/8100190599ea3854c6219bc65c0529afb102030d/libraryapi/src/main/java/com/library/api/libraryapi/GlobalExceptionHandler.java#L22C24-L22C45

**Comment by FiNTiKUglY** [comment]
Исправил, действительно копипаст очень подвёл
