### ISSUE TITLE
здесь !smth.isPresent() можно поменять на smth.isEmpty()

### ISSUE THREAD

**Issue by YULIYA2001** [FiNTiKUglY/pract#19]
https://github.com/FiNTiKUglY/pract/blob/fb1d24b27879854ba3907b12af9e2e7cee147e73/libraryapi/src/main/java/com/library/api/libraryapi/services/AuthorService.java#L33C13-L33C35

**Comment by FiNTiKUglY** [comment]
Изменил, добавил во все сервисы
