### ISSUE TITLE
Здесь ошибка (нужно добавить throws в сигнатуру метода, иначе не запуститься)

### ISSUE THREAD

**Issue by YULIYA2001** [FiNTiKUglY/pract#20]
https://github.com/FiNTiKUglY/pract/blob/fb1d24b27879854ba3907b12af9e2e7cee147e73/libraryapi/src/main/java/com/library/api/libraryapi/controllers/AuthorController.java#L30C5-L33C6

хорошо бы аналогичную обработку на NotFound в бд сделать для всех сущностей

**Comment by FiNTiKUglY** [comment]
Сделал, исправил

**Comment by FiNTiKUglY** [comment]
Во всех сущностях тоже

**Comment by YULIYA2001** [comment]
Тогда закрывайте issue )
