### ISSUE TITLE
Note

### ISSUE THREAD

**Issue by YULIYA2001** [FiNTiKUglY/pract#21]
var - не лучшая практика - сильно ухудшает читаемость кода

https://github.com/FiNTiKUglY/pract/blob/998b97cc3232b201951d1573c545d3feb855ba94/libraryapi/src/main/java/com/library/api/libraryapi/security/ApplicationUserDetailsService.java#L32

**Comment by FiNTiKUglY** [comment]
я помню вы писали, но я уже тогда всё это отписал, в будущем учту

**Comment by FiNTiKUglY** [comment]
написал код точнее*
