### ISSUE TITLE
Это базовый урл, повторяется во всех файлах, его нужно отдельно вынести

### ISSUE THREAD

**Issue by YULIYA2001** [FiNTiKUglY/pract#22]
https://github.com/FiNTiKUglY/pract/blob/a21883daae04ec454b38ea8dd10fc44c7c0b99c6/libraryReact/src/api/authService.js#L5C9-L5C36

**Comment by FiNTiKUglY** [comment]
не подскажете как лучше это сделать? константу в файле и импортить её?

**Comment by YULIYA2001** [comment]
Лучше всего выносить в файл окружения .env. Но можно и константу сделать.
Если вынести в файл окружения, то примерно так: https://www.linkedin.com/pulse/how-use-environment-files-env-react-app-muhammad-sameem
Там нужно добавить .env файл, измнеить package.json, чтобы при запуске использовался этот файл, и заменить сами пути. В базовый урл выносится обычно "http://bla-bla:port". И когда будете писать составные пути там нужно использовать кавычку, которая на букве Ё (process.env.REACT_APP_URL + \`/api/...\`). Если повторения в одном файле, то там можно прописать еще и константу.
