### ISSUE TITLE
react

### ISSUE THREAD

**Issue by YULIYA2001** [FiNTiKUglY/pract#24]
- Как работает обработка ошибок c бэка?
- На фронте реакт нет проверок ВООБЩЕ. Я запустила: что не ввод - красный экран с ошибкой. Не тпроверок на ввод букв в поле цифр (сразу ошибка).
- Обработчик исключений не перехватывает исключение (запрос с неверным id 'http://localhost:8080/api/genres/delete/...' не возвращает ожидаемый 404)
- При update ожидается, что на фронте будут не пустые поля, а предзаполненные, чтобы изменить и действительно сделать update, а не по новой создавать

**Comment by FiNTiKUglY** [comment]
Исправил, добавлю экран ошибки позднее, как разберусь нормально
