### ISSUE TITLE
program to interfaces, not implementation

### ISSUE THREAD

**Issue by YULIYA2001** [FiNTiKUglY/pract#5]
Есть такой принцип 'program to interfaces, not implementation', он входит в Принцип замены Лисков, который входит в SOLID. Поэтому, если его придерживаться, стоит писать  ```List<IEntity> authors = new ArrayList<>(); ```

https://github.com/FiNTiKUglY/pract/blob/d584a1ae37aa9c4d8e0a899dc6c49372f58b3c39/task2/src/repositories/AuthorRepository.java#L23

**Comment by FiNTiKUglY** [comment]
исправлено
