### ISSUE TITLE
NullPointer?

### ISSUE THREAD

**Issue by YULIYA2001** [FiNTiKUglY/pract#6]
Логируется warning-сообщение и явно возвращается null в connection, а дальше этот null передается в репозитории, а там вылетит NullPointerException? Попробуйте явно прописать null в connection и посмотреть, как работает меню.

https://github.com/FiNTiKUglY/pract/blob/d584a1ae37aa9c4d8e0a899dc6c49372f58b3c39/task2/src/App.java#L30C13-L30C25

**Comment by FiNTiKUglY** [comment]
исправлено
