### ISSUE TITLE
Исключение

### ISSUE THREAD

**Issue by YULIYA2001** [FiNTiKUglY/pract#7]
Можно на 4 курсе минимальную проверочку от ввода строки предусмотреть? Если я запущу приложение оно же не должно валится при промахе по кнопке...

https://github.com/FiNTiKUglY/pract/blob/bd6791c528b9ded4fa4465a022be27d243a8dfde/task2/src/App.java#L40

**Comment by FiNTiKUglY** [comment]
исправлено
