### ISSUE TITLE
Декомпозиция

### ISSUE THREAD

**Issue by YULIYA2001** [FiNTiKUglY/pract#8]
Большие секции с вложенным кодом и отдельной логикой в switch лучше вынести в отдельные методы с соответствующими названиями добавления, обновления и т.д.

https://github.com/FiNTiKUglY/pract/blob/bd6791c528b9ded4fa4465a022be27d243a8dfde/task2/src/App.java#L43C17-L73C18

**Comment by FiNTiKUglY** [comment]
исправлено
