### ISSUE TITLE
бд, jdbc

### ISSUE THREAD

**Issue by YULIYA2001** [FiNTiKUglY/pract#9]
- В бд у связующих таблиц нет первичного ключа. Возможно, имеет смысл добавить составной первичный ключ (из двух айдишников)? 
- Мы придерживаемся единственного числа при названии таблиц (это править не нужно, просто к сведению).
- Ориентировачное время 12, фактическое 6. Здесь не должно быть наоборот (изначально было 6:6)? 
- У Вас нет связи многие-ко-многим в коде. В базе реализация через дополнительную таблицу, это верно, а в коде я не вижу связи таблиц orders-books и books-genres. Например, для реализации многие-ко-многим можно добавить в класс Order поле List<Long> bookIds (в заказе есть список книг, и аналогично у книги есть список жанров).
- Для читаемости лучше писать  ```@Override``` при реализации методов интерфейса (это касается репозиториев)
- Опять же для читаемости лучше не использовать var (можно не править)

**Comment by FiNTiKUglY** [comment]
исправил
